// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBank.Context;

namespace OnlineBank.Migrations
{
    [DbContext(typeof(OnlineBankContext))]
    [Migration("20190404103645_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBank.Models.Account", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("accTypeId");

                    b.Property<float>("balance");

                    b.Property<int>("bankId");

                    b.Property<string>("city");

                    b.Property<string>("email");

                    b.Property<DateTime>("expDate");

                    b.Property<float>("limit");

                    b.Property<string>("loginStatus");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<string>("phone");

                    b.Property<string>("username");

                    b.HasKey("accountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OnlineBank.Models.AccountTransaction", b =>
                {
                    b.Property<int>("accTransId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("accountId");

                    b.Property<int>("transId");

                    b.HasKey("accTransId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("OnlineBank.Models.AccountType", b =>
                {
                    b.Property<int>("accTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accTypeName");

                    b.HasKey("accTypeId");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("OnlineBank.Models.BankBranch", b =>
                {
                    b.Property<int>("bankId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bankLocation");

                    b.Property<string>("bankName");

                    b.HasKey("bankId");

                    b.ToTable("BankBranches");
                });

            modelBuilder.Entity("OnlineBank.Models.Transaction", b =>
                {
                    b.Property<int>("transId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("transAmount");

                    b.Property<DateTime>("transDate");

                    b.Property<int>("typeId");

                    b.HasKey("transId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnlineBank.Models.TransactionType", b =>
                {
                    b.Property<int>("typeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("typeName");

                    b.HasKey("typeId");

                    b.ToTable("TransactionTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
